spring:
  profiles:
    active: ${SPRING_PROFILE:dev}

  boot:
    admin:
      client:
        url: ${ADMIN_MONITOR_URL}  # URL of your Admin Server
        username: ${ADMIN_MONITOR_USERNAME}
        password: ${ADMIN_MONITOR_PASSWORD}

        instance:
          service-base-url: ${SERVICE_BASE_URL}
          management-base-url: ${MANAGEMENT_BASE_URL}
          metadata:
            user.name: ${ACTUATOR_USERNAME}
            user.password: ${ACTUATOR_PASSWORD}
  
  application:
    name: openapi-server

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none  # Hibernate will not manage schema; Liquibase handles it

    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-root.yaml

logging:
  level:
    org:
      springframework:
        security: ${LOG_LEVEL_SECURITY}  # default to INFO if not set

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all actuator endpoints

  endpoint:
    health:
      show-details: when_authorized
      roles: [ "ACTUATOR" ]

    env:
      show-values: when_authorized
      roles: [ "ACTUATOR" ]

    configprops:
      show-values: when_authorized
      roles: [ "ACTUATOR" ]

  info:
    env:
      enabled: true  # Enable the info endpoint with environment details
